### PR TITLE
Math magician app setup 

### PR DESCRIPTION
**Pull request by melashu**
# In this setup I have done the following things 

- Initialize react app using `npx create-react app` command 
- Install linter configuration.
- Create development branch and make it default branch 
- Update readme file on development branch

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @melashu 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow proper gitflow

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by prolajumokeoni — COMMENTED** [review]
Hi @melashu  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
You have submitted a project, that does not follow proper gitflow, kindly check the [general requirements ](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_setup.md#general-requirements)of this project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by melashu** [comment]
Hi @prolajumokeoni, Sorry, I sent frequent request reviews without checking my PR, because on my dashboard I haven't seen the Request Changed label as usual.

**Comment by FrederickMih** [comment]
Hi @melashu, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**You'll need to follow the Correct GitHub workflow before your project can be reviewed. You need to create a feature branch, make the development branch the default branch, and create a PR from the feature to develop branch. [ReadMore...](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
